### ISSUE TITLE
result display

### ISSUE THREAD

**Issue by JoseSachango** [ChefJayPeek/petResume#5]
- [ ] picture slider
- [ ] breed information

**Comment by JoseSachango** [comment]
It gives me a 404 error depending on what dog name I put in. Even if the dog is found within the response array.

error -> "Failed to load resource: the server responded with a status of 404 ()"

**Comment by FanghanHu** [comment]
pls share the query link tomorrow, we can look at it together.

**Comment by JoseSachango** [comment]
https://api.thedogapi.com/v1/breeds?api_key=6eb49e4c-fb5a-4a63-84f3-04f3d2b8bf46
@FanghanHu

**Comment by JoseSachango** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/62193290/99481777-75fae000-2920-11eb-91c8-49c98ea02613.png)

**Comment by JoseSachango** [comment]
Maybe it's because the array is broken up in this way? Idk...
